#ifndef LIBK_DEFS_H
#define LIBK_DEFS_H

#define SYS_CALL_FAMILY_IO      0x01
#define SYS_CALL_FAMILY_MEM     0x02
#define SYS_CALL_FAMILY_PROC    0x03
#define SYS_CALL_FAMILY_EVENT   0x04
#define SYS_CALL_FAMILY_STDIO   0x10
#define SYS_CALL_FAMILY_IO_FILE 0x11
#define SYS_CALL_FAMILY_IO_DIR  0x12
#define SYS_CALL_FAMILY_KERNEL  0x20

#define SYS_CALL_IO_OPEN  ((SYS_CALL_FAMILY_IO << 16) | 0x0001)
#define SYS_CALL_IO_CLOSE ((SYS_CALL_FAMILY_IO << 16) | 0x0002)
#define SYS_CALL_IO_READ  ((SYS_CALL_FAMILY_IO << 16) | 0x0003)
#define SYS_CALL_IO_WRITE ((SYS_CALL_FAMILY_IO << 16) | 0x0004)
#define SYS_CALL_IO_SIZE  ((SYS_CALL_FAMILY_IO << 16) | 0x0005)

#define SYS_CALL_MEM_MALLOC  ((SYS_CALL_FAMILY_MEM << 16) | 0x0001)
#define SYS_CALL_MEM_REALLOC ((SYS_CALL_FAMILY_MEM << 16) | 0x0002)
#define SYS_CALL_MEM_FREE    ((SYS_CALL_FAMILY_MEM << 16) | 0x0003)

#define SYS_CALL_PROC_EXIT           ((SYS_CALL_FAMILY_PROC << 16) | 0x0001)
#define SYS_CALL_PROC_ABORT          ((SYS_CALL_FAMILY_PROC << 16) | 0x0002)
#define SYS_CALL_PROC_PANIC          ((SYS_CALL_FAMILY_PROC << 16) | 0x0003)
#define SYS_CALL_PROC_REG_SIG        ((SYS_CALL_FAMILY_PROC << 16) | 0x0004)
#define SYS_CALL_PROC_GETPID         ((SYS_CALL_FAMILY_PROC << 16) | 0x0005)
#define SYS_CALL_PROC_QUEUE_EVENT    ((SYS_CALL_FAMILY_PROC << 16) | 0x0006)
#define SYS_CALL_PROC_YIELD          ((SYS_CALL_FAMILY_PROC << 16) | 0x0007)
#define SYS_CALL_PROC_EXEC           ((SYS_CALL_FAMILY_PROC << 16) | 0x0008)
#define SYS_CALL_PROC_SET_FOREGROUND ((SYS_CALL_FAMILY_PROC << 16) | 0x0009)
#define SYS_CALL_PROC_WAIT_PID       ((SYS_CALL_FAMILY_PROC << 16) | 0x000a)

#define SYS_CALL_PROC_LIST_OPEN
#define SYS_CALL_PROC_LIST_CLOSE
#define SYS_CALL_PROC_LIST_READ
#define SYS_CALL_PROC_LIST_

#define SYS_CALL_EVENT_PULL  ((SYS_CALL_FAMILY_EVENT << 16) | 0x0001)
#define SYS_CALL_EVENT_TIME  ((SYS_CALL_FAMILY_EVENT << 16) | 0x0002)
#define SYS_CALL_EVENT_SLEEP ((SYS_CALL_FAMILY_EVENT << 16) | 0x0003)

// #define SYS_CALL_STDIO_PUTC 0x1000
// #define SYS_CALL_STDIO_PUTS 0x1001

// #define SYS_CALL_IO_FILE_OPEN  0x1101
// #define SYS_CALL_IO_FILE_CLOSE 0x1102
// #define SYS_CALL_IO_FILE_READ  0x1103
// #define SYS_CALL_IO_FILE_WRITE 0x1104
// #define SYS_CALL_IO_FILE_SEEK  0x1105
// #define SYS_CALL_IO_FILE_TELL  0x1106

// #define SYS_CALL_IO_DIR_OPEN  0x1201
// #define SYS_CALL_IO_DIR_CLOSE 0x1202
// #define SYS_CALL_IO_DIR_READ  0x1203
// #define SYS_CALL_IO_DIR_SEEK  0x1205
// #define SYS_CALL_IO_DIR_TELL  0x1206

#define SYS_CALL_KERNEL_DESCRIBE ((SYS_CALL_FAMILY_KERNEL << 16) | 0x0001)

#endif // LIBK_DEFS_H
