# set(CMAKE_SYSTEM_NAME Generic-ELF)
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR ${CROSS_ARCH})
# TODO: does this do anything?
#set(CMAKE_SYSTEM_VERSION 12.2.0)
set(CMAKE_SYSTEM_VERSION ${CROSS_GCC_VERSION})

# set(tools /home/devel/gcc-4.7-linaro-rpi-gnueabihf)
set(CMAKE_C_COMPILER ${CROSS_PREFIX}/bin/${CROSS_ARCH}-gcc)
set(CMAKE_C_FLAGS "-g -Werror -ffreestanding")
set(CMAKE_C_COMPILER_WORKS 1)

set(CMAKE_CXX_COMPILER ${CROSS_PREFIX}/bin/${CROSS_ARCH}-g++)
set(CMAKE_CXX_FLAGS "-g -Werror -ffreestanding")
set(CMAKE_CXX_COMPILER_WORKS 1)

set(CMAKE_AR "${CROSS_PREFIX}/bin/${CROSS_ARCH}-ar" CACHE FILEPATH "" FORCE)

set(CMAKE_LINKER "${CROSS_PREFIX}/bin/${CROSS_ARCH}-ld")
set(CMAKE_LINKER_FLAGS "HELLO WORLD")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
