name: PR Title Check

on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  check-pr-title:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: automas-dev/reusable-workflows/increment_version@enforce_title
        id: version
        with:
          dry-run: true
          enforce-conventional-commit: true

  check:
    runs-on: ubuntu-latest
    if: always()

    needs:
      - check-pr-title

    timeout-minutes: 1

    steps:
      - uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
